#!/usr/bin/env python3
"""
theme-apply - unified theme switcher for the Hyprland desktop.

Renders Jinja2 templates per app using a chosen palette + visual,
backs up existing files, writes new ones, sends reload signals.
"""

from __future__ import annotations

import argparse
import datetime
import os
import random
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

try:
    import jinja2
except ImportError:
    sys.stderr.write("error: jinja2 not installed. run: pip install --user jinja2\n")
    sys.exit(2)

# ---------------------------------------------------------------------------
# constants
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent
PALETTES_DIR = ROOT / "palettes"
VISUALS_DIR = ROOT / "visuals"
TEMPLATES_DIR = ROOT / "templates"
STATE_FILE = ROOT / "state.toml"
BACKUP_ROOT = Path.home() / "Development" / "Logs" / "theme-switcher-backups"
HOME = Path.home()

# Dispatch table: app key -> (template filename, output path, reload command list-or-None)
APPS: dict[str, dict] = {
    "ags": {
        "template": "ags.css.j2",
        "output": HOME / ".config/ags/style.css",
        "reload": ["sh", "-c", "pkill -f 'gjs.*ags.js' ; ( sleep 0.5 ; /home/vib1240n/.config/ags/run-bar.sh </dev/null >/dev/null 2>&1 ) &"],
    },
    "rust-widgets": {
        "template": "rw.css.j2",
        "output": HOME / ".config/rw/style.css",
        "reload": ["rw", "reload"],
    },
    "cliphist-gui": {
        "template": "cliphist-gui.css.j2",
        "output": HOME / ".config/cliphist-gui/style.css",
        "reload": ["cliphist-gui", "--reload"],
    },
    "launch-gui": {
        "template": "launch-gui.css.j2",
        "output": HOME / ".config/launch-gui/style.css",
        "reload": ["launch-gui", "--reload"],
    },
    "kitty": {
        "template": "kitty.conf.j2",
        "output": HOME / ".config/kitty/colors.conf",
        "reload": ["sh", "-c", "pkill -SIGUSR1 -x kitty || true"],
    },
    "hyprland": {
        "template": "hypr-colors.conf.j2",
        "output": HOME / ".config/hypr/colors.conf",
        "reload": ["hyprctl", "reload"],
    },
    "hypr-layerrules": {
        "template": "layerrules.conf.j2",
        "output": HOME / ".config/hypr/layerrules-themed.conf",
        "reload": ["hyprctl", "reload"],
    },
    "hyprlock": {
        "template": "hyprlock-colors.conf.j2",
        "output": HOME / ".config/hypr/hyprlock-colors.conf",
        "reload": None,
    },
    "waybar": {
        "template": "waybar.css.j2",
        "output": HOME / ".config/waybar/colors.css",
        "reload": ["sh", "-c", "pkill -SIGUSR2 waybar || true"],
    },
}

# ---------------------------------------------------------------------------
# jinja filters
# ---------------------------------------------------------------------------


def filter_hex(value: str) -> str:
    """Strip the leading # from a hex color. #1a2b3c -> 1a2b3c"""
    return value.lstrip("#")


def filter_alpha_hex(value: float) -> str:
    """Convert a 0.0-1.0 opacity to a 2-char hex byte. 0.5 -> 80"""
    n = max(0, min(255, int(round(value * 255))))
    return f"{n:02x}"


def filter_rgba_hypr(args) -> str:
    """
    Build a Hyprland rgba(rrggbbaa) string from (hex, opacity).
    Usage: {{ (color.shadow, opacity.shadow) | rgba_hypr }}
    """
    hex_val, opacity = args
    return f"rgba({filter_hex(hex_val)}{filter_alpha_hex(opacity)})"


# ---------------------------------------------------------------------------
# utility helpers
# ---------------------------------------------------------------------------


def log(msg: str, *, verbose: bool = False, level: str = "info") -> None:
    if level == "error":
        sys.stderr.write(f"[error] {msg}\n")
    elif level == "warn":
        sys.stderr.write(f"[warn] {msg}\n")
    elif verbose:
        sys.stderr.write(f"[info] {msg}\n")


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def list_stems(d: Path) -> list[str]:
    if not d.is_dir():
        return []
    return sorted(p.stem for p in d.glob("*.toml"))


def read_state() -> dict:
    if not STATE_FILE.exists():
        return {}
    try:
        return load_toml(STATE_FILE)
    except Exception as e:
        log(f"could not parse state.toml: {e}", level="warn")
        return {}


def write_state(palette: str, visual: str) -> None:
    ts = datetime.datetime.now().isoformat(timespec="seconds")
    STATE_FILE.write_text(
        f'# auto-generated by theme-apply.py - do not hand-edit\n'
        f'palette = "{palette}"\n'
        f'visual = "{visual}"\n'
        f'applied_at = "{ts}"\n'
    )


# ---------------------------------------------------------------------------
# context flattening
# ---------------------------------------------------------------------------


def flatten_opacity(visual: dict, dark: bool) -> dict:
    v = {k: dict(val) if isinstance(val, dict) else val for k, val in visual.items()}
    op = v.get("opacity", {})
    mode_key = "dark" if dark else "light"
    if mode_key in op:
        flat = op[mode_key]
        v["opacity"] = flat
    else:
        log("visual has no opacity.dark/light split; using as-is", level="warn")
    return v


def build_context(palette: dict, visual: dict) -> dict:
    is_dark = palette.get("meta", {}).get("dark", True)
    v_flat = flatten_opacity(visual, is_dark)
    return {
        "palette": palette,
        "visual": v_flat,
        "color": palette.get("color", {}),
        "opacity": v_flat.get("opacity", {}),
        "radius": v_flat.get("radius", {}),
        "sizing": v_flat.get("sizing", {}),
        "meta": {
            "palette_name": palette.get("meta", {}).get("name", "?"),
            "visual_name": visual.get("meta", {}).get("name", "?"),
            "dark": is_dark,
        },
    }


# ---------------------------------------------------------------------------
# render + write
# ---------------------------------------------------------------------------


def make_env() -> jinja2.Environment:
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(TEMPLATES_DIR)),
        undefined=jinja2.StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    env.filters["hex"] = filter_hex
    env.filters["alpha_hex"] = filter_alpha_hex
    env.filters["rgba_hypr"] = filter_rgba_hypr
    return env


def backup_file(src: Path, backup_dir: Path) -> None:
    if not src.exists():
        return
    rel = src.relative_to(HOME) if str(src).startswith(str(HOME)) else Path(*src.parts[1:])
    dst = backup_dir / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def render_app(env: jinja2.Environment, app_key: str, app: dict, ctx: dict) -> str:
    tpl = env.get_template(app["template"])
    return tpl.render(**ctx)


def reload_app(app_key: str, app: dict, *, verbose: bool) -> None:
    cmd = app.get("reload")
    if cmd is None:
        log(f"{app_key}: no reload command (skipped)", verbose=verbose)
        return
    try:
        subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
        log(f"{app_key}: reload dispatched", verbose=verbose)
    except FileNotFoundError:
        log(f"{app_key}: reload command not found, skipping", level="warn")
    except Exception as e:
        log(f"{app_key}: reload failed: {e}", level="warn")


# ---------------------------------------------------------------------------
# main apply
# ---------------------------------------------------------------------------


def do_apply(
    palette_name: str,
    visual_name: str,
    *,
    only: list[str] | None = None,
    dry_run: bool = False,
    no_reload: bool = False,
    verbose: bool = False,
) -> int:
    palette_path = PALETTES_DIR / f"{palette_name}.toml"
    visual_path = VISUALS_DIR / f"{visual_name}.toml"

    if not palette_path.exists():
        log(f"palette not found: {palette_name}", level="error")
        return 1
    if not visual_path.exists():
        log(f"visual not found: {visual_name}", level="error")
        return 1

    palette = load_toml(palette_path)
    visual = load_toml(visual_path)
    ctx = build_context(palette, visual)
    env = make_env()

    targets = list(APPS.items()) if only is None else [(k, APPS[k]) for k in only if k in APPS]
    if only is not None and len(targets) != len(only):
        unknown = set(only) - set(APPS)
        log(f"unknown app(s): {', '.join(unknown)}", level="warn")

    ts = datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")
    backup_dir = BACKUP_ROOT / ts

    log(f"palette={palette_name} visual={visual_name} dark={ctx['meta']['dark']}", verbose=verbose)
    log(f"backup_dir={backup_dir}", verbose=verbose)

    errors = 0
    rendered: list[tuple[str, dict, str]] = []

    for app_key, app in targets:
        tpl_path = TEMPLATES_DIR / app["template"]
        if not tpl_path.exists():
            log(f"{app_key}: template missing ({app['template']}), skipping", level="warn")
            continue
        try:
            out = render_app(env, app_key, app, ctx)
            rendered.append((app_key, app, out))
        except jinja2.UndefinedError as e:
            log(f"{app_key}: template references undefined variable: {e}", level="error")
            errors += 1
        except jinja2.TemplateSyntaxError as e:
            log(f"{app_key}: template syntax error: {e}", level="error")
            errors += 1
        except Exception as e:
            log(f"{app_key}: render failed: {e}", level="error")
            errors += 1

    if errors:
        log(f"{errors} render error(s); aborting before any write", level="error")
        return 1

    if dry_run:
        for app_key, app, out in rendered:
            print(f"# ===== {app_key} -> {app['output']} =====")
            print(out)
        return 0

    backup_dir.mkdir(parents=True, exist_ok=True)
    for app_key, app, out in rendered:
        dst = app["output"]
        backup_file(dst, backup_dir)
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(out)
        log(f"{app_key}: wrote {dst}", verbose=verbose)

    if not no_reload:
        for app_key, app, _ in rendered:
            reload_app(app_key, app, verbose=verbose)

    write_state(palette_name, visual_name)
    log("done", verbose=verbose)
    return 0


# ---------------------------------------------------------------------------
# cli
# ---------------------------------------------------------------------------


def cmd_list(kind: str) -> int:
    if kind == "palettes":
        for n in list_stems(PALETTES_DIR):
            print(n)
    elif kind == "visuals":
        for n in list_stems(VISUALS_DIR):
            print(n)
    return 0


def cmd_current() -> int:
    s = read_state()
    if not s:
        print("(no state)")
        return 0
    print(f"palette: {s.get('palette', '?')}")
    print(f"visual:  {s.get('visual', '?')}")
    print(f"applied: {s.get('applied_at', '?')}")
    return 0


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="theme-apply", description="Unified theme switcher")
    p.add_argument("--palette", help="palette name (file stem in palettes/)")
    p.add_argument("--visual", help="visual name (file stem in visuals/)")
    p.add_argument("--only", help="comma-separated app keys to render (default: all)")
    p.add_argument("--dry-run", action="store_true", help="render to stdout, do not write")
    p.add_argument("--no-reload", action="store_true", help="write files but do not reload apps")
    p.add_argument("--list-palettes", action="store_true")
    p.add_argument("--list-visuals", action="store_true")
    p.add_argument("--list-apps", action="store_true")
    p.add_argument("--current", action="store_true", help="show currently applied theme")
    p.add_argument("--random", action="store_true", help="pick a random palette + visual")
    p.add_argument("--verbose", "-v", action="store_true")

    args = p.parse_args(argv)

    if args.list_palettes:
        return cmd_list("palettes")
    if args.list_visuals:
        return cmd_list("visuals")
    if args.list_apps:
        for k in APPS:
            print(k)
        return 0
    if args.current:
        return cmd_current()

    state = read_state()
    palette = args.palette or state.get("palette")
    visual = args.visual or state.get("visual")

    if args.random:
        ps = list_stems(PALETTES_DIR)
        vs = list_stems(VISUALS_DIR)
        if not ps or not vs:
            log("no palettes or visuals found", level="error")
            return 1
        palette = random.choice(ps)
        visual = random.choice(vs)
        log(f"random pick: {palette} + {visual}", verbose=True)

    if not palette or not visual:
        log("need --palette and --visual (or prior state, or --random)", level="error")
        p.print_usage(sys.stderr)
        return 2

    only = [s.strip() for s in args.only.split(",")] if args.only else None

    return do_apply(
        palette,
        visual,
        only=only,
        dry_run=args.dry_run,
        no_reload=args.no_reload,
        verbose=args.verbose,
    )


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
