[meta]
name = "nord"
dark = true

[color]
bg          = "#2e3440"
bg_elevated = "#3b4252"
bg_critical = "#3d2329"

fg          = "#eceff4"
fg_pure     = "#ffffff"

border      = "#4c566a"
shadow      = "#000000"

accent      = "#88c0d0"

red         = "#bf616a"
yellow      = "#ebcb8b"
green       = "#a3be8c"
blue        = "#81a1c1"

vim_normal  = "#81a1c1"
vim_insert  = "#a3be8c"
vim_bg      = "#2e3440"
